"""add column

Revision ID: 0c8c60774552
Revises: e25f9df3649b
Create Date: 2024-07-01 14:03:01.563001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8c60774552'
down_revision = 'e25f9df3649b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
