"""add column

Revision ID: 3896a9dc7400
Revises: 0c8c60774552
Create Date: 2024-07-01 14:07:04.941666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3896a9dc7400'
down_revision = '0c8c60774552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('plants', sa.Column('image', sa.String(length=200), nullable=False))
    op.add_column('plants', sa.Column('price', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'plants', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='unique')
    op.drop_column('plants', 'price')
    op.drop_column('plants', 'image')
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
